name: Test - Multiple Architectures

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - main

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    
    strategy:

      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [8, 10, 12, 14]
        architecture:
          - x64

    steps:

      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Setup NodeJS (${{ matrix.node-version }}) - ${{ matrix.architecture }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}

      - name: Verify Architecture & Node version (via verify script)
        run: sh scripts/tests/verify_arch.sh "${{ matrix.os }}" "${{ matrix.architecture }}" "${{ matrix.node-version }}"
        shell: bash
